FROM nvcr.io/nvidia/tensorflow:24.09-tf2-py3
#
#ENV https_proxy "http://http-p.srv.cc.suzuka-ct.ac.jp:8080"
#ENV http_proxy "http://http-p.srv.cc.suzuka-ct.ac.jp:8080"

RUN apt-get update && apt-get install -y git ffmpeg && apt-get clean