version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app/:/app/"
    command: python vocal-remover/inference.py --input /app/music.wav --gpu 0